/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root.tsx'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login.tsx'
import { Route as OrdersIndexRouteImport } from './routes/orders.index.tsx'
import { Route as OrdersIdRouteImport } from './routes/orders.$id.tsx'
import { Route as ProductsIndexRouteImport } from './routes/products.index.tsx'
import { Route as ProductsIdRouteImport } from './routes/products.$id.tsx'
import { Route as ReelsIndexRouteImport } from './routes/reels.index.tsx'
import { Route as ReelsEditRouteImport } from './routes/reels.edit.tsx'
import { Route as ReelsFeaturedRouteImport } from './routes/reels.featured.tsx'
import { Route as RequestsIndexRouteImport } from './routes/requests.index.tsx'
import { Route as RequestsIdRouteImport } from './routes/requests.$id.tsx'
import { Route as WhatsappIndexRouteImport } from './routes/whatsapp.index.tsx'
import { Route as WhatsappBroadcastRouteImport } from './routes/whatsapp.broadcast.tsx'
import { Route as WhatsappAnalyticsNotificationIdRouteImport } from './routes/whatsapp.analytics.$notificationId.tsx'
import { Route as WhatsappItemItemIdRouteImport } from './routes/whatsapp.item.$itemId.tsx'
import { Route as WhatsappSendItemIdRouteImport } from './routes/whatsapp.send.$itemId.tsx'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsIndexRoute = ReelsIndexRouteImport.update({
  id: '/reels/',
  path: '/reels/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsEditRoute = ReelsEditRouteImport.update({
  id: '/reels/edit',
  path: '/reels/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ReelsFeaturedRoute = ReelsFeaturedRouteImport.update({
  id: '/reels/featured',
  path: '/reels/featured',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappIndexRoute = WhatsappIndexRouteImport.update({
  id: '/whatsapp/',
  path: '/whatsapp/',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappBroadcastRoute = WhatsappBroadcastRouteImport.update({
  id: '/whatsapp/broadcast',
  path: '/whatsapp/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappAnalyticsNotificationIdRoute =
  WhatsappAnalyticsNotificationIdRouteImport.update({
    id: '/whatsapp/analytics/$notificationId',
    path: '/whatsapp/analytics/$notificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const WhatsappItemItemIdRoute = WhatsappItemItemIdRouteImport.update({
  id: '/whatsapp/item/$itemId',
  path: '/whatsapp/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatsappSendItemIdRoute = WhatsappSendItemIdRouteImport.update({
  id: '/whatsapp/send/$itemId',
  path: '/whatsapp/send/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reels/edit': typeof ReelsEditRoute
  '/reels/featured': typeof ReelsFeaturedRoute
  '/requests/$id': typeof RequestsIdRoute
  '/whatsapp/broadcast': typeof WhatsappBroadcastRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reels/': typeof ReelsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/whatsapp/analytics/$notificationId': typeof WhatsappAnalyticsNotificationIdRoute
  '/whatsapp/item/$itemId': typeof WhatsappItemItemIdRoute
  '/whatsapp/send/$itemId': typeof WhatsappSendItemIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reels/edit': typeof ReelsEditRoute
  '/reels/featured': typeof ReelsFeaturedRoute
  '/requests/$id': typeof RequestsIdRoute
  '/whatsapp/broadcast': typeof WhatsappBroadcastRoute
  '/orders': typeof OrdersIndexRoute
  '/products': typeof ProductsIndexRoute
  '/reels': typeof ReelsIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/whatsapp': typeof WhatsappIndexRoute
  '/whatsapp/analytics/$notificationId': typeof WhatsappAnalyticsNotificationIdRoute
  '/whatsapp/item/$itemId': typeof WhatsappItemItemIdRoute
  '/whatsapp/send/$itemId': typeof WhatsappSendItemIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/orders/$id': typeof OrdersIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/reels/edit': typeof ReelsEditRoute
  '/reels/featured': typeof ReelsFeaturedRoute
  '/requests/$id': typeof RequestsIdRoute
  '/whatsapp/broadcast': typeof WhatsappBroadcastRoute
  '/orders/': typeof OrdersIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/reels/': typeof ReelsIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/whatsapp/': typeof WhatsappIndexRoute
  '/whatsapp/analytics/$notificationId': typeof WhatsappAnalyticsNotificationIdRoute
  '/whatsapp/item/$itemId': typeof WhatsappItemItemIdRoute
  '/whatsapp/send/$itemId': typeof WhatsappSendItemIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orders/$id'
    | '/products/$id'
    | '/reels/edit'
    | '/reels/featured'
    | '/requests/$id'
    | '/whatsapp/broadcast'
    | '/orders/'
    | '/products/'
    | '/reels/'
    | '/requests/'
    | '/whatsapp/'
    | '/whatsapp/analytics/$notificationId'
    | '/whatsapp/item/$itemId'
    | '/whatsapp/send/$itemId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/orders/$id'
    | '/products/$id'
    | '/reels/edit'
    | '/reels/featured'
    | '/requests/$id'
    | '/whatsapp/broadcast'
    | '/orders'
    | '/products'
    | '/reels'
    | '/requests'
    | '/whatsapp'
    | '/whatsapp/analytics/$notificationId'
    | '/whatsapp/item/$itemId'
    | '/whatsapp/send/$itemId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/orders/$id'
    | '/products/$id'
    | '/reels/edit'
    | '/reels/featured'
    | '/requests/$id'
    | '/whatsapp/broadcast'
    | '/orders/'
    | '/products/'
    | '/reels/'
    | '/requests/'
    | '/whatsapp/'
    | '/whatsapp/analytics/$notificationId'
    | '/whatsapp/item/$itemId'
    | '/whatsapp/send/$itemId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ReelsEditRoute: typeof ReelsEditRoute
  ReelsFeaturedRoute: typeof ReelsFeaturedRoute
  RequestsIdRoute: typeof RequestsIdRoute
  WhatsappBroadcastRoute: typeof WhatsappBroadcastRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  ReelsIndexRoute: typeof ReelsIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  WhatsappIndexRoute: typeof WhatsappIndexRoute
  WhatsappAnalyticsNotificationIdRoute: typeof WhatsappAnalyticsNotificationIdRoute
  WhatsappItemItemIdRoute: typeof WhatsappItemItemIdRoute
  WhatsappSendItemIdRoute: typeof WhatsappSendItemIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/': {
      id: '/reels/'
      path: '/reels'
      fullPath: '/reels/'
      preLoaderRoute: typeof ReelsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/edit': {
      id: '/reels/edit'
      path: '/reels/edit'
      fullPath: '/reels/edit'
      preLoaderRoute: typeof ReelsEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reels/featured': {
      id: '/reels/featured'
      path: '/reels/featured'
      fullPath: '/reels/featured'
      preLoaderRoute: typeof ReelsFeaturedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/': {
      id: '/whatsapp/'
      path: '/whatsapp'
      fullPath: '/whatsapp/'
      preLoaderRoute: typeof WhatsappIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/broadcast': {
      id: '/whatsapp/broadcast'
      path: '/whatsapp/broadcast'
      fullPath: '/whatsapp/broadcast'
      preLoaderRoute: typeof WhatsappBroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/analytics/$notificationId': {
      id: '/whatsapp/analytics/$notificationId'
      path: '/whatsapp/analytics/$notificationId'
      fullPath: '/whatsapp/analytics/$notificationId'
      preLoaderRoute: typeof WhatsappAnalyticsNotificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/item/$itemId': {
      id: '/whatsapp/item/$itemId'
      path: '/whatsapp/item/$itemId'
      fullPath: '/whatsapp/item/$itemId'
      preLoaderRoute: typeof WhatsappItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/whatsapp/send/$itemId': {
      id: '/whatsapp/send/$itemId'
      path: '/whatsapp/send/$itemId'
      fullPath: '/whatsapp/send/$itemId'
      preLoaderRoute: typeof WhatsappSendItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductsIdRoute: ProductsIdRoute,
  ReelsEditRoute: ReelsEditRoute,
  ReelsFeaturedRoute: ReelsFeaturedRoute,
  RequestsIdRoute: RequestsIdRoute,
  WhatsappBroadcastRoute: WhatsappBroadcastRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  ReelsIndexRoute: ReelsIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  WhatsappIndexRoute: WhatsappIndexRoute,
  WhatsappAnalyticsNotificationIdRoute: WhatsappAnalyticsNotificationIdRoute,
  WhatsappItemItemIdRoute: WhatsappItemItemIdRoute,
  WhatsappSendItemIdRoute: WhatsappSendItemIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
