/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DesignStudioRouteImport } from './routes/design-studio'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as RequestsIndexRouteImport } from './routes/requests.index'
import { Route as RequestsIdRouteImport } from './routes/requests.$id'
import { Route as CategoryCategoryIndexRouteImport } from './routes/category.$category.index'
import { Route as CategoryCategorySubRouteImport } from './routes/category.$category.$sub'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignStudioRoute = DesignStudioRouteImport.update({
  id: '/design-studio',
  path: '/design-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIdRoute = RequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIndexRoute = CategoryCategoryIndexRouteImport.update({
  id: '/category/$category/',
  path: '/category/$category/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategorySubRoute = CategoryCategorySubRouteImport.update({
  id: '/category/$category/$sub',
  path: '/category/$category/$sub',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/design-studio': typeof DesignStudioRoute
  '/wishlist': typeof WishlistRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/category/$category/$sub': typeof CategoryCategorySubRoute
  '/category/$category/': typeof CategoryCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/design-studio': typeof DesignStudioRoute
  '/wishlist': typeof WishlistRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/orders': typeof OrdersIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/category/$category/$sub': typeof CategoryCategorySubRoute
  '/category/$category': typeof CategoryCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/design-studio': typeof DesignStudioRoute
  '/wishlist': typeof WishlistRoute
  '/orders/$id': typeof OrdersIdRoute
  '/product/$id': typeof ProductIdRoute
  '/requests/$id': typeof RequestsIdRoute
  '/orders/': typeof OrdersIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/category/$category/$sub': typeof CategoryCategorySubRoute
  '/category/$category/': typeof CategoryCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/design-studio'
    | '/wishlist'
    | '/orders/$id'
    | '/product/$id'
    | '/requests/$id'
    | '/orders/'
    | '/requests/'
    | '/category/$category/$sub'
    | '/category/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/design-studio'
    | '/wishlist'
    | '/orders/$id'
    | '/product/$id'
    | '/requests/$id'
    | '/orders'
    | '/requests'
    | '/category/$category/$sub'
    | '/category/$category'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/design-studio'
    | '/wishlist'
    | '/orders/$id'
    | '/product/$id'
    | '/requests/$id'
    | '/orders/'
    | '/requests/'
    | '/category/$category/$sub'
    | '/category/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  DesignStudioRoute: typeof DesignStudioRoute
  WishlistRoute: typeof WishlistRoute
  OrdersIdRoute: typeof OrdersIdRoute
  ProductIdRoute: typeof ProductIdRoute
  RequestsIdRoute: typeof RequestsIdRoute
  OrdersIndexRoute: typeof OrdersIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  CategoryCategorySubRoute: typeof CategoryCategorySubRoute
  CategoryCategoryIndexRoute: typeof CategoryCategoryIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-studio': {
      id: '/design-studio'
      path: '/design-studio'
      fullPath: '/design-studio'
      preLoaderRoute: typeof DesignStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$id': {
      id: '/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof RequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category/': {
      id: '/category/$category/'
      path: '/category/$category'
      fullPath: '/category/$category/'
      preLoaderRoute: typeof CategoryCategoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$category/$sub': {
      id: '/category/$category/$sub'
      path: '/category/$category/$sub'
      fullPath: '/category/$category/$sub'
      preLoaderRoute: typeof CategoryCategorySubRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  DesignStudioRoute: DesignStudioRoute,
  WishlistRoute: WishlistRoute,
  OrdersIdRoute: OrdersIdRoute,
  ProductIdRoute: ProductIdRoute,
  RequestsIdRoute: RequestsIdRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  CategoryCategorySubRoute: CategoryCategorySubRoute,
  CategoryCategoryIndexRoute: CategoryCategoryIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
